etf_weights:
  path: '/equity/etf_weights/'
equity_universe:
  path: '/equity/universe/'
equity_prices:
  path: '/equity/prices/'
futures:
  path: '/futures/'
  partition: 
    freq: 'monthly'
    first: 2010-06-01
futures_cont:
  path: '/futures-cont/'
  partition:
    freq: 'monthly'
    first: 2010-06-01
