equities:
  etf_weights:
    path: '/equity/etf_weights/'
  universe:
    path: '/equity/universe/'
  prices:
    path: '/equity/prices/'
futures:
  discrete:
    path: '/futures/'
    partition: 
      freq: 'monthly'
      first: 2010-06-01
  cont:
    path: '/futures-cont/'
    partition:
      freq: 'monthly'
      first: 2010-06-01
model:
  factors:
    path: '/factors/'
    partition:
      freq: 'monthly'
      first: 2010-06-01
  universe:
    path: '/model-universe/'
