'6A':
  name: Australian Dollar
  asset_class: FX
  sector: Developed
'6B':
  name: British Pound
  asset_class: FX
  sector: Developed
'6C':
  name: Canadian Dollar
  asset_class: FX
  sector: Developed
'6E':
  name: Euro FX
  asset_class: FX
  sector: Developed
'6J':
  name: Japanese Yen
  asset_class: FX
  sector: Developed
'6L':
  name: Mexican Peso
  asset_class: FX
  sector: Emerging
'6M':
  name: Brazilian Real
  asset_class: FX
  sector: Emerging
'6N':
  name: New Zealand Dollar
  asset_class: FX
  sector: Developed
'6S':
  name: Swiss Franc
  asset_class: FX
  sector: Developed
'6Z':
  name: South African Rand
  asset_class: FX
  sector: Emerging
'ALI':
  name: Aluminum
  asset_class: Metals
  sector: Base
'CL':
  name: Crude Oil
  asset_class: Energy
  sector: Light Sweet
'DC':
  name: Class III Milk
  asset_class: Agriculture
  sector: Dairy
'EHR':
  name: E-mini FTSE Emerging Index
  asset_class: Equity
  sector: Emerging
'EMD':
  name: E-mini S&P MidCap 400
  asset_class: Equity
  sector: US
'ES':
  name: E-mini S&P 500
  asset_class: Equity
  sector: US
'GC':
  name: Gold
  asset_class: Metals
  sector: Precious
'GF':
  name: Feeder Cattle
  asset_class: Agriculture
  sector: Livestock
'HE':
  name: Lean Hogs
  asset_class: Agriculture
  sector: Livestock
'HG':
  name: Copper
  asset_class: Metals
  sector: Base
'HO':
  name: NY Harbor ULSD
  asset_class: Energy
  sector: Refined
'HRC':
  name: Hot Rolled Coil Steel
  asset_class: Metals
  sector: Industrial
'KE':
  name: KC HRW Wheat
  asset_class: Agriculture
  sector: Grains
'LBR':
  name: Lumber
  asset_class: Agriculture
  sector: Softs
'LE':
  name: Live Cattle
  asset_class: Agriculture
  sector: Livestock
'M2K':
  name: Micro Russell 2000
  asset_class: Equity
  sector: US
'MBT':
  name: Micro Bitcoin
  asset_class: Crypto
  sector: Digital
'MCL':
  name: Micro Crude Oil
  asset_class: Energy
  sector: Light Sweet
'MES':
  name: Micro E-mini S&P 500
  asset_class: Equity
  sector: US
'MET':
  name: Micro Ether
  asset_class: Crypto
  sector: Digital
'MGC':
  name: Micro Gold
  asset_class: Metals
  sector: Precious
'MNG':
  name: Micro Natural Gas
  asset_class: Energy
  sector: Natural Gas
'MNQ':
  name: Micro E-mini Nasdaq-100
  asset_class: Equity
  sector: US
'MYM':
  name: Micro E-mini Dow
  asset_class: Equity
  sector: US
'NG':
  name: Natural Gas
  asset_class: Energy
  sector: Natural Gas
'NIY':
  name: Nikkei/USD
  asset_class: Equity
  sector: Asia
'NKD':
  name: Nikkei 225
  asset_class: Equity
  sector: Asia
'PA':
  name: Palladium
  asset_class: Metals
  sector: Precious
'PL':
  name: Platinum
  asset_class: Metals
  sector: Precious
'PRK':
  name: Pork Cutout
  asset_class: Agriculture
  sector: Livestock
'RB':
  name: RBOB Gasoline
  asset_class: Energy
  sector: Refined
'RP':
  name: Euro/British Pound
  asset_class: FX
  sector: Cross Rates
'RTY':
  name: E-mini Russell 2000
  asset_class: Equity
  sector: US
'RX':
  name: Euro-Bund
  asset_class: Rates
  sector: European
'SI':
  name: Silver
  asset_class: Metals
  sector: Precious
'SIR':
  name: Indian Rupee
  asset_class: FX
  sector: Emerging
'SR3':
  name: 3-Month SOFR
  asset_class: Rates
  sector: US
'TBF3':
  name: 3-Year T-Note
  asset_class: Rates
  sector: US
'TN':
  name: Ultra 10-Year US T-Notes
  asset_class: Rates
  sector: US
'UB':
  name: Ultra T-Bond
  asset_class: Rates
  sector: US
'YM':
  name: E-mini Dow
  asset_class: Equity
  sector: US
'Z3N':
  name: 3-Month Euribor
  asset_class: Rates
  sector: European
'ZB':
  name: 30-Year T-Bond
  asset_class: Rates
  sector: US
'ZC':
  name: Corn
  asset_class: Agriculture
  sector: Grains
'ZF':
  name: 5-Year T-Note
  asset_class: Rates
  sector: US
'ZL':
  name: Soybean Oil
  asset_class: Agriculture
  sector: Oilseeds
'ZM':
  name: Soybean Meal
  asset_class: Agriculture
  sector: Oilseeds
'ZN':
  name: 10-Year T-Note
  asset_class: Rates
  sector: US
'ZO':
  name: Oats
  asset_class: Agriculture
  sector: Grains
'ZR':
  name: Rough Rice
  asset_class: Agriculture
  sector: Grains
'ZS':
  name: Soybeans
  asset_class: Agriculture
  sector: Oilseeds
'ZT':
  name: 2-Year T-Note
  asset_class: Rates
  sector: US
'ZW':
  name: Chicago SRW Wheat
  asset_class: Agriculture
  sector: Grains
